move_base_flex:
  ros__parameters:
    global_frame: 'map'
    robot_frame: 'base_link'
    odom_topic: 'Spot/odometry'

    use_sim_time: false
    force_stop_at_goal: true
    force_stop_on_cancel: true

    planners: ['octo_planner']
    octo_planner:
      type: 'astar_2d_planner/Astar2dPlanner'
      cost_limit: 0.95
      publish_vector_field: true
      obstacle_inflation_radius: 0.6  # meters - safety distance from obstacles
      inflation_decay_rate: 0.5       # how quickly cost decays from obstacle edge
    planner_patience: 10.0
    planner_max_retries: 2

    controllers: ['octo_controller']
    octo_controller:
      type: 'octo_controller/OctoController'
      ang_vel_factor: 0.25
      lin_vel_factor: 0.5
      max_lin_velocity: 0.5
      max_ang_velocity: 0.25

    controller_patience: 10.0 
    controller_max_retries: 4
    dist_tolerance: 0.5
    angle_tolerance: 6.0
    
    controller_frequency: 10.0
